### ISSUE TITLE
Describe `mappings/default.json`

### ISSUE THREAD

**Issue by mankoff** [hiromu2000/mintcash#1]
Hi,

I'm trying to use your code to convert from Mint to GnuCash. I think I have figured out most of the issues but am getting the following error:

```
ArgumentError: Could not parse rfc1738 URL from string '/path/to/database.gnucash'
```

I think it might be due to `mappings/default.json`. Can you provide documentation for this file? For example, one line is:

```
    "ASSET": {"name": "Assets", "gnucash_type": "ASSET"},
```

Do these terms need to be Mint? Should I customize this file based on my Mint accounts? Or do I need to pre-populate a GnuCash database with these empty accounts?

**Comment by mankoff** [comment]
Fixed. Perhaps an update to piecash. Replace all `uri_conn=self.dbname` with just `self.dbname`.

**Comment by hiromu2000** [comment]
Hi,

I'm glad to hear that my code is useful for other people.

I'm using the latest version (0.12.0) of piecash and it works.
`uri_conn=self.dbname` assumes that `self.dbname` starts from protocol (e.g., mysql://, sqlite://).
In your case, `self.dbname` should be `sqlite:///path/to/database.gnucash`.
When a sqlite3 **file** is used, just `self.dbname` without `uri_conn` also works; but when mysql or postgresql is used, it should be `uri_conn=self.dbname`.

See [here](https://github.com/sdementen/piecash/blob/master/docs/source/tutorial/new_objects/create_book.rst) for more details.
